### ISSUE TITLE
Plugin does not use jdk from toolchains plugin 

### ISSUE THREAD

**Issue by minesunny** [mojohaus/exec-maven-plugin#352] opened 2022-12-14 07:08 UTC
toolchain know the path of java11, but exec plugin still use my system java8 path
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/98507458/207529223-4ef45d41-71dd-47d7-a97f-511c46752493.png">

**Comment by slawekjaranowski** [comment] 2023-11-11 15:05
duplicate of #49

**Closed by slawekjaranowski** 2023-11-11 15:05 UTC
